name: Build and test Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t cybersecurity_intel_app .

    - name: Run simple test of container
      run: |
        docker run --rm \
          --env EXA_API_KEY=${{ secrets.EXA_API_KEY }} \
          --env OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          cybersecurity_intel_app
